nav:
  - 'ホーム':
    - 'スタートガイド': index.md
    - 'カルダノノードの構築':
      - 'エアギャップ作成':
        - 'エアギャップとは': airgap/index.md
        - 'Windowsの場合':
          - 'Docker-airgapの構築': airgap/01-windows-docker-airgap.md
          - 'VirtualBox with ctoolの構築': airgap/02-windows-virtualbox-with-ctool.md
      - 'Ubuntu Server の設定': cardano-node/01-ubuntu-server-setup.md
    - 'その他':
      - 'Midnight':
        - 'Preview ノードインストール': midnight/01-install-preview-node.md
        - 'Preview トポロジー設定': midnight/02-setup-preview-topology.md
        - 'BPキーを作成': midnight/03-setup-bp-keys.md
        - 'アドレスを作成': midnight/04-create-addresses.md
        - 'ステークアドレスの登録': midnight/05-register-stake-address.md
        - 'ステークプールの登録': midnight/06-register-stake-pool.md
        - 'Partner-Chains-Node の構築': midnight/11-partner-chain-node.md
        - 'Midnight-Node の構築': midnight/12-midnight-node.md
      - 'ipfsサーバーの構築':
        - 'KuboによるIPFSサーバーの構築': ./other/ipfs/01-kubo.md
      - 'NFTの発行':
        - 'cardano-cliを使用したNFTの発行': ./other/nft/01-cardano-cli.md

  - 'マニュアルの書き方':
    - 'VSCode の入手とインストール': manual/01-vscode-installation.md
    - 'リポジトリのクローン': manual/02-clone-repository.md
    - 'マニュアルの編集': manual/03-write-manual.md
    - 'プルリクエストの作成': manual/04-create-pull-request.md
  - 'このサイトについて':
    - 'SPO-Kissaについて': about/spo-kissa.md
    - '寄稿者': about/contributors.md
    - 'ライセンス': about/license.md

theme:
  name: material
  custom_dir: overrides
  language: ja
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: github
      primary: brown
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
#    - navigation.sections
#    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking
#    - navigation.instant
    - navigation.footer
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_lang_class: true
      anchor_linenums: true
      line_spans: __span
      pygments_style: monokai
      linenums: false
  - toc:
      permalink: true
  - footnotes
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/w7DYV3mSQb
    - icon: fontawesome/brands/twitter
      link: https://x.com/SpoKissa
    - icon: fontawesome/brands/github
      link: https://github.com/spo-kissa
  alternate:
    - name: English
      link: /en/
      lang: en
  homepage: https://spo-kissa.org
  generator: false
site_name: SPO-Kissa Documentation
docs_dir: docs
site_url: https://spo-kissa.org
copyright: Copyright &copy; 2025 SPO Kissa.
repo_url: https://github.com/spo-kissa/docs
repo_name: spo-kissa/docs
extra_css:
  - css/custom.css
