site_name: SPO-Kissa Documentation
site_url: https://spo-kissa.org
theme:
  name: material
  language: ja
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: brown
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: brown
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  alternate:
    - name: English
      link: /en/
      lang: en
  homepage: https://spo-kissa.org
  generator: false
copyright: Copyright &copy; 2025 SPO Kissa.
repo_url: https://github.com/spo-kissa/docs
repo_name: spo-kissa/docs
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - attr_list
nav:
  - 'ホーム':
    - 'スタートガイド': index.md
    - 'エアギャップ作成': airgap/index.md
    - 'Windowsの場合':
      - 'Docker-airgapの構築': airgap/01-windows-docker-airgap.md
      - 'VirtualBox with ctoolの構築': airgap/02-windows-virtualbox-with-ctool.md
  - 'マニュアルの書き方':
    - 'VSCode の入手とインストール': manual/01-vscode-installation.md
    - 'リポジトリのクローン': manual/02-clone-repository.md
    - 'マニュアルの編集': manual/03-write-manual.md
    - 'プルリクエストの作成': manual/04-create-pull-request.md
  - 'このサイトについて':
    - 'SPO-Kissaについて': about/spo-kissa.md
    - '寄稿者': about/contributors.md
    - 'ライセンス': about/license.md
